version: "3.7"
services:
    ganache:
        build: .
        container_name: ganache
        restart: always
        ports:
            - "7545:7545"
        volumes:
            - ./build/:/app/build/
            - ./contracts/:/app/contracts/
            - ./interfaces/:/app/interfaces/
            - ./migrations/:/app/migrations/
            - ./tests/:/app/tests/
            - ./package.json:/app/package.json
            - ./truffle.js:/app/truffle.js
 